# Generated by Django 5.2.3 on 2025-06-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.IntegerField(default=0)),
                ('safe_stock', models.IntegerField(help_text='Minimum stock to avoid risk of stockout')),
                ('reorder_point', models.IntegerField(help_text='When stock reaches this level, reorder')),
                ('lead_time', models.IntegerField(help_text='Supplier lead time in days')),
                ('fulfillment_time', models.IntegerField(help_text='Internal restock time in days')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.product')),
            ],
        ),
    ]
