# Generated by Django 5.2.3 on 2025-06-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_productinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_inr',
            new_name='price',
        ),
    ]
