# Generated by Django 5.2.3 on 2025-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_price_inr_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(default='shelf', max_length=20),
        ),
    ]
