# Generated by Django 5.2.3 on 2025-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_product_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
