# Generated by Django 5.2.3 on 2025-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_sales_units_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lead_time', models.IntegerField(help_text='Delivery lead time in days')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
