# Generated by Django 5.2.3 on 2025-07-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_type',
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_storage',
            field=models.CharField(default='ambient', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.supplier'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='units_sold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
