# Generated by Django 5.2.3 on 2025-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_product_id_remove_product_storage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='shelf_life',
            field=models.CharField(default='3 days', help_text='max time the product should be on store shelf'),
        ),
    ]
