# Generated by Django 5.2.3 on 2025-07-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_productinventory_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perishable', 'Perishable'), ('non_perishable', 'Non-Perishable'), ('electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_storage',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('cold', 'Cold Storage'), ('dry', 'Dry Storage')], default='ambient', max_length=100),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='shelf_life',
            field=models.CharField(default='3 days', help_text='Maximum time product should stay on shelf'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time',
            field=models.IntegerField(help_text='Supplier lead time in days'),
        ),
    ]
