# Generated by Django 5.2.3 on 2025-07-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_storage',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('cold', 'Cold Storage'), ('dry', 'Dry Storage'), ('freeze', 'deep freezer')], default='ambient', max_length=100),
        ),
    ]
