# Generated by Django 5.2.3 on 2025-07-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_product_type_of_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='fulfillment_time_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=10),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='lead_time_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=10),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='fulfillment_time',
            field=models.IntegerField(help_text='Internal restock time'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='lead_time',
            field=models.IntegerField(help_text='Supplier lead time'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='shelf_life',
            field=models.CharField(default='3 days', help_text='Maximum time product should stay on shelf', max_length=20),
        ),
    ]
