# Generated by Django 5.2.3 on 2025-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_productinventory_fulfillment_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='oreder_frequency',
            field=models.IntegerField(default=3, help_text='how frequent the product should be ordered days'),
        ),
    ]
