# Generated by Django 5.2.3 on 2025-07-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_productinventory_oreder_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='oreder_frequency',
            new_name='order_frequency',
        ),
    ]
